title: "Mostafa | Cybersecurity Notes"
description: "SOC, SIEM, DFIR, Windows, Linux and cybersecurity labs."

baseurl: "/cybersecurity-blog"

markdown: kramdown

permalink: /posts/:title/

exclude:
  - README.md
