# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: mosta5amahmoud/cybersecurity-blog
  branch: main
  auth_methods:
    - oauth
    - token

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "Articles"
    label_singular: "Article"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"

    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD HH:mm:ss ZZ"

      - label: "Categories"
        name: "categories"
        widget: "list"
        default:
          - "Cybersecurity"

      - label: "Description"
        name: "description"
        widget: "text"
        required: false

      - label: "Body"
        name: "body"
        widget: "markdown"
